Putting pawns in board
leoflood/ezejedrez pull request #12
Opened 2021-04-26 13:10 UTC by ezejerez

2021-04-26 13:15 UTC, leoflood approved these changes

2021-04-26 20:26 UTC, hhaamm requested changes

2021-04-26 20:26 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Esto es turbio porque rompe el encapsulamiento. O sea, funciona y está bien, pero no es buena práctica. Lo ideal sería que chessBoard tenga un método addPiece (si es que no lo tiene), donde le pases tipo de pieza, color y posición y lo agregue.

2021-04-26 20:26 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
"rompe el encapsulamiento" quiere decir que vos agarrás una referencia de algo y la modificás afuera, eso es medio peligroso. Es mejor tener un método "addPiece" (y testearlo) en chess. Te dejo la tarea de hacer el addPiece y testearlo. Además nos va a servir para poder hacer tableros custom (y eso nos sirve para poder hacer tests mas fáciles).

2021-04-26 20:26 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Además no me convence que esto funcione, chessBoard no es un array?

2021-04-26 20:27 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Lo que digo es que este código debería verse así:

```
chess.addPiece('king', 'white', 4, 3);
const chessBoard = chess.getBoard();
// ...
```

2021-04-26 20:29 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Ah, estoy viendo que cambiaron la implementación del board, que ahora es una matriz. Entonces, olvidate lo que dije que no funcionaba. Aún así sostengo que hay que hacer el addPiece. Entre otras cosas el addPiece podría chequear que no haya actualmente una pieza ahí.

2021-04-26 20:29 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Y si hay una pieza tiene que tirar una excepción.

2021-04-26 20:53 UTC, ezejerez commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Dale, una vez que termine lo de los tests de los peones me pongo a solucionar esto

2021-04-29 22:58 UTC, hhaamm requested changes

2021-04-29 22:58 UTC, hhaamm commented on App.js
> +    chessBoard[4][3] = { pieceType: 'king', color: 'white' };
Acordate de crear/usar addPiece en la línea 22, el resto lo veo bien.

2021-04-29 23:37 UTC, leoflood requested changes
Hacer addPiece con TDD 

1) Test 1: hacer el test de la funcion addPiece, despues de agregar una pieza por ejemplo en 4,4, que se fije que antes de agregarla no había una pieza ahí, y después si. Ademas se deberá fijar que la cantidad de piezas es igual a la cantidad de piezas de antes + 1.

2) Test 2: hacer que agregue una pieza en una posicion donde ya hay otra pieza y que tire excepcion "There is already a piece in that position". Además se deberá fijar que la cantidad de piezas sigue siendo la misma que antes.

Nota: recomiendo para poder hacer estos tests, crear un nuevo metodo que sea getPieces, que devuelva un array con todas las piezas del tablero

2021-05-03 21:01 UTC, hhaamm commented on src/core/chess.js
> +<<<<<<< HEAD
Esta PR está toda rota

2021-05-03 23:39 UTC, leoflood approved these changes

2021-05-04 00:19 UTC, hhaamm approved these changes

2021-05-04 00:19 UTC, hhaamm commented on App.js
> +    // chess.addPiece('king', 'white', 4, 3);
Esto no entendí por qué lo comentaron

2021-05-04 00:19 UTC, hhaamm commented on src/core/chess.js
> +  __movePiece(fromX, fromY, toX, toY) {
Perfecto, esto indica que el método es privado

2021-05-04 00:19 UTC, hhaamm commented on src/core/chess.js
> +    const addIfIsAnEmptySquare = (mX, mY) => {
ok, ojo que acá estas usando scopes de la función de arriba y puede resultar confuso

2021-05-04 00:19 UTC, hhaamm commented on src/core/chess.js
> +  getPieces() {
ok, me gusta el nombre

2021-05-04 00:19 UTC, hhaamm commented on src/core/chess.js
> +    const pieces = arr.filter((piece) => piece.pieceType);
No entiendo bien esto, hay piezas que no tienen definido el piece type? No sería un estado inválido eso?

2021-05-04 00:19 UTC, hhaamm commented on src/core/test/chess.test.js
> +  expect(chess.hasPiece(4, 3)).toBe(false);
En líneas generales en TDD hacemos solo expectations al final, igual lo dejo pasar porque no hace falta ser tan estrictos. Pero está bueno tener esa convención porque sino es confuso

2021-05-04 00:19 UTC, hhaamm commented on src/core/test/chess.test.js
> +test(`It shouldn't be possible to add a piece in a invalid position`, () => {
*an invalid position

2021-05-04 00:19 UTC, hhaamm commented on src/core/test/chess.test.js
> +  expect(t).toThrow(`There's already a piece in that position`);
Estos errores habría que moverlos a constantes de la clase Chess. Pero para otra PR

2021-05-04 00:19 UTC, hhaamm commented on src/core/test/chess.test.js
> +  chess.addPiece('pawn', 'black', 4, 5);
Honestamente prefiero el setBoard pero bueno, si quieren hacerlo así está bien.

2021-05-04 00:39 UTC, leoflood commented on App.js
> +    // chess.addPiece('king', 'white', 4, 3);
jajajajaa

2021-05-04 00:39 UTC, leoflood commented on src/core/chess.js
> +    const pieces = arr.filter((piece) => piece.pieceType);
get board as array convierte la matrix en un array incluidos los 0

2021-05-04 00:40 UTC, merged