some methods are now refactored and there`s 6 new tests
leoflood/ezejedrez pull request #13
Opened 2021-04-29 22:56 UTC by ezejerez

please don't be ugly

2021-04-29 23:06 UTC, hhaamm requested changes

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('Wait should play first', () => {
*white

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('Pawns movements 3 (black)', () => {
Hay mucho código tipo:

```
expect(chess.getPiece(0, 2)).not.toBe(0);
expect(chess.getPiece(0, 1)).toBe(0);
```

Ahí tenes que usar "hasPiece" que se entiende mucho mas (además que devuelva "0" si no hay nada es medio cualquiera, debería tirar una excepción o devolver null/undefined o, en todo caso, si estás usando números, tendrías que ponerlo en una constante, algo como NO_PIECE).

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('White pawn cannot move 2 squares if Y != 1', () => {
Este test está mal. Tenes que mover también el peón negro porque sino puede fallar pero por el motivo equivocado (que no es su turno).

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('White pawn cannot move 2 squares if Y != 1', () => {
Por cierto actuamente esto te permite que mueva dos veces las blancas (o negras)?

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('Black pawn cannot move 2 squares if Y != 6', () => {
Ídem caso anterior

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +  expect(chess.getPiece(4, 4)).not.toBe(0);
usar hasPiece

2021-04-29 23:06 UTC, hhaamm commented on src/core/test/chess.test.js
> +  expect(chess.getPiece(3, 3)).not.toBe(0);
Usar hasPiece

2021-05-01 01:13 UTC, ezejerez commented on src/core/test/chess.test.js
> +test('Wait should play first', () => {
JAJAJ

2021-05-01 02:25 UTC, ezejerez commented on src/core/test/chess.test.js
> +test('White pawn cannot move 2 squares if Y != 1', () => {
El metodo movePiece no cambia el turno. Lo otro ya fue corregi2

2021-05-01 13:44 UTC, leoflood commented on src/core/chess.js
> +  }
@ezejerez acá si haces

return this.getPiece(x, y) !== 0;

también funcionaría. Pero así como está también está bien

2021-05-01 13:45 UTC, leoflood commented on src/core/chess.js
> +  }
Porque

`{piece: "king", color: "white} !== 0; // true
0 !== 0; // false
`

2021-05-01 13:46 UTC, leoflood commented on src/core/test/chess.test.js
> +});
bien

2021-05-01 13:47 UTC, leoflood commented on src/core/test/chess.test.js
> +  expect(chess.hasPiece(0, 1)).toBe(false);
chet0

2021-05-01 13:48 UTC, leoflood commented on src/core/test/chess.test.js
> +  chess.move(7, 1, 7, 2);
acá agregaría un comentario para que se entienda por que haces esto

algo como
// primero movemos una pieza blanca para que sea el turno de las negras

2021-05-01 13:49 UTC, leoflood approved these changes

2021-05-01 13:50 UTC, leoflood commented on src/core/test/chess.test.js
> +test('Pawns movements 3 (black)', () => {
listo

2021-05-01 22:33 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('White pawn cannot move 2 squares if Y != 1', () => {
Ah ok, en ese caso el test me parece medio raro pero ok

2021-05-01 22:36 UTC, hhaamm commented on src/core/test/chess.test.js
> +  const t = () => {
Esto es un poco lo que yo decía, acá el test se vuelve confuso porque estás usando a la vez move y movePiece en el mismo código (mismo caso anterior). Yo la verdad évitaría eso, es mas, te diría que movePiece no deberías poder usarlo desde afuera (o sea en los tests).

2021-05-01 22:36 UTC, hhaamm commented on src/core/test/chess.test.js
> +  const t = () => {
Para reempazar a movePIece en los tests en que necesites hacer eso por algún motivo usaría un método setBoard o similar, donde directamente seteas el board que vos querés con las posiciones que vos quieras y el turno que vos quieras. Me parece mucho mas entendible que mezclar movePiece con move.

2021-05-01 22:36 UTC, hhaamm commented on src/core/test/chess.test.js
> +  const t = () => {
Igual eso se puede hacer en otra PR si querés, no se.

2021-05-01 22:40 UTC, ezejerez commented on src/core/test/chess.test.js
> +  const t = () => {
Me parece mejor hacerlo en otra pr directamente eso, así queda más ordenado. Y sobre todo porque tengo que hacer la funcionalidad de los tests que agregué ayer todavía

2021-05-01 22:42 UTC, merged