Knight class
leoflood/ezejedrez pull request #26
Opened 2021-05-26 13:15 UTC by ezejerez

2021-05-27 17:40 UTC, leoflood requested changes
corregir eso q te puse

2021-05-27 17:40 UTC, leoflood commented on src/core/pieces/knight.ts
> +    ];
voy a suponer que esto está bien

2021-05-27 17:40 UTC, leoflood commented on src/core/test/chess.test.ts
> +    });
fijate que aca estas testeando la funcion getPieceMovements, pero esto lo pusiste adentro del describe de move

2021-05-27 17:45 UTC, ezejerez commented on src/core/pieces/knight.ts
> +    ];
supones bien xD

2021-05-27 17:52 UTC, leoflood approved these changes

2021-05-27 20:51 UTC, hhaamm requested changes
Sacar el código repetido de Knight y, si hay, en King tmb

2021-05-27 20:51 UTC, hhaamm commented on src/core/pieces/knight.ts
> +    const knightPossibleCaptures = [
Este código está repetido. Fijate de ponerlo afuera o en algún lado (de este archivo) para que no se repita. Podría ser una constante, onda, const MOVEMENTS = { ... } afuera de la clase.

2021-05-27 20:51 UTC, hhaamm commented on src/core/pieces/knight.ts
> +    const knightPossibleCaptures = [
Hacé lo mismo con la clase King si es que pasa lo mismo ahí.

2021-05-27 20:51 UTC, hhaamm commented on src/core/test/chess.test.ts
> +    test('Black Knight can jump over pieces to reach its destination', () => {
no se si tiene mucho sentido este segundo tests, tuviste que hacerlo (o sea, te falló la primera vez?)? Igual no digo de sacarlo, solo me llama la atención

2021-05-27 21:12 UTC, ezejerez commented on src/core/test/chess.test.ts
> +    test('Black Knight can jump over pieces to reach its destination', () => {
Hice el de las blancas y las negras al mismo tiempo osea que me fallaron los dos al mismo tiempo, pero puedo hacer que sea solo uno y que testee solo el caso de las blancas ya que a la funcionalidad le es indiferente el color

2021-05-27 21:15 UTC, hhaamm commented on src/core/test/chess.test.ts
> +    test('Black Knight can jump over pieces to reach its destination', () => {
Si, para mi con uno solo está bien. En ese caso tambien sacale el color de la descripción del test ya que sería para ambos colores. "Knight can jump.. " etc.

2021-05-27 22:31 UTC, ezejerez commented on src/core/pieces/knight.ts
> +    const knightPossibleCaptures = [
Esto lo resolví en otro branch, me confundí. Cuando suba el de los alfiles se va a ver el cambio

2021-05-28 14:15 UTC, hhaamm approved these changes

2021-05-28 14:15 UTC, hhaamm commented on src/core/pieces/knight.ts
> +    const knightPossibleCaptures = [
oka

2021-05-28 14:15 UTC, hhaamm commented on src/core/test/chess.test.ts
> +      expect(movements.find((m) => m.x === 4 && m.y === 4)).not.toBe(undefined);
Acá si te fijas hay bocha de código repetido que se podría reducir un poco. Igual lo dejamos para otra PR. Como identificar código repetido? Fijate que lo unico que cambia son los numeritos, el resto es igual.

2021-05-28 18:00 UTC, merged