Pawn movements
leoflood/ezejedrez pull request #4
Opened 2021-04-01 22:03 UTC by ezejerez

:(

2021-04-02 00:16 UTC, leoflood approved these changes

2021-04-02 14:23 UTC, leoflood commented on src/core/chess.js
> +    }
esto capaz podria quedar mejor
`return this.turnNumber % == 2 ? "black" : "white"`
una sola linea

2021-04-02 14:40 UTC, hhaamm commented on src/core/test/chess.test.js
> +test('Pawns movements 3', () => {
Los nombres de los tests son medio chotos y en algún momento habría que refactorizar los tests pero por ahora está bien.

2021-04-02 14:54 UTC, hhaamm requested changes
Tareas:
- Pasar el find a getPiece(x, y) para mayor claridad
- Renombrar movePiece y sacarle parámetros innecesarios (si no podemos encontrar un nombre piola es porque no se entiende lo que hace)
- Responder la duda que dejé de la función move.

2021-04-02 14:54 UTC, hhaamm commented on src/core/chess.js
> +      const piece = board.find((piece) => piece.x === x && piece.y === 1);
Este find se podría pasar a un método por sí mismo, no? Onda getPiece(x, y), que te devuelva la descripción de la pieza en ese lugar. Esto nos permitiría seguramente eliminar algo de código repetido PERO PRINCIPALMENTE aclarar el código existente. Está bueno que el código se pueda leer en algún punto como lenguaje humano (idealmente, nunca se logra del todo).

Entonces yo haría un nuevo método:

```
getPiece(x, y) {
    // que devuelva la pieza de la posición x, y
}
```

Y la línea de arriba la reemplazaría por:

```
const piece = this.getPiece(x, 1);
```

2021-04-02 14:54 UTC, hhaamm commented on src/core/chess.js
> +      const piece = board.find((piece) => piece.x === x && piece.y === 1);
Fijate si podes hacer ese refactor que me parece le daría mas legibilidad al código @ezejerez

2021-04-02 14:54 UTC, hhaamm commented on src/core/chess.js
> +  movePiece(x, board, fromX, fromY, toX, toY) {
El nombre de esta función quedó un poco raro porque solo mueve peones? También es medio al pedo pasarle el board creo porque el board pertenece al objeto, se puede usar this.board.

Habría que buscarle un buen nombre a la función que represente lo que hace, viendo qué parámetros se le pasan. Se te ocurre uno?

2021-04-02 14:54 UTC, hhaamm commented on src/core/chess.js
> +  move(fromX, fromY, toX, toY) {
Mas adelante también estaría bueno comentar el código, si bien como todavía lo estamos construyendo por ahora no lo haremos ya que los métodos pueden cambiar. Igual en este caso, te parece que la interfaz del método (o sea el nombre y los parámetros) van a cambiar mucho?

2021-04-02 15:04 UTC, leoflood commented on src/core/chess.js
> +  movePiece(x, board, fromX, fromY, toX, toY) {
o this.getBoard() ya que venimos usando ese

2021-04-02 15:05 UTC, leoflood requested changes
ver los comments que dejamos hugo y yo

2021-04-03 14:37 UTC, leoflood approved these changes
Hay cosas por mejorar pero creo que mejor verlas en Discord, aproba3

2021-04-10 20:07 UTC, leoflood commented
@hhaamm cuando puedas revisar de vuelta esta PR, creo que las sugerencias ya fueron resueltas

2021-04-11 23:44 UTC, hhaamm approved these changes

2021-04-12 20:26 UTC, merged