square-colors-added
leoflood/ezejedrez pull request #5
Opened 2021-04-02 03:21 UTC by ezejerez

:D

2021-04-02 13:29 UTC, leoflood commented on src/ui/square.jsx
>          console.log(`Has presionado el cuadrado ${x} ${y}`);
En general está bien porque funciona, pero se podría mejorar:

* La función determineColor recibe dos parametros: x e y
Estos parámetros no son necesarios ya que afuera, dentro del scope de Square ya sabe quién es x e y porque los recibe y estos no cambian, entonces para arreglar esto y que quede mas prolijo tenes dos opciónes: 

  1) sacar determineColor afuera de Square y dejarla como está (recibiendo parámetros x e y)
  2) o sacarle los parámetros x e y asi usa los mismos que el de Square

Yo personalmente prefiero la primera ya que sacás esa funcion del elemento porque no es necesaria que esté ahi y ademas cada vez que hagas un nuevo Square va a tener su propia funcion determineColor, en cambio si la sacas, todos los Square usan la misma, la del archivo, ocupando menos memoria

2021-04-02 13:29 UTC, leoflood commented on src/ui/square.jsx
>          console.log(`Has presionado el cuadrado ${x} ${y}`);
No que que opina mi buen amigo @hhaamm

2021-04-02 14:52 UTC, hhaamm commented on src/ui/square.jsx
>          console.log(`Has presionado el cuadrado ${x} ${y}`);
No se si es muy relevante pero la opción i) está bien para mi.

2021-04-02 14:55 UTC, hhaamm approved these changes

2021-04-02 15:06 UTC, leoflood requested changes
ver el temita de determineColor

2021-04-03 01:47 UTC, leoflood approved these changes
aproba3

2021-04-03 01:47 UTC, merged