King piece task
leoflood/ezejedrez pull request #9
Opened 2021-04-22 13:07 UTC by ezejerez

And his name is John Cenaaaaaaaaaaaaa

2021-04-22 13:22 UTC, leoflood approved these changes

2021-04-23 00:39 UTC, hhaamm commented
No entiendo bien, parecen los mismos cambios que https://github.com/leoflood/ezejedrez/pull/8

2021-04-23 00:42 UTC, ezejerez commented
> No entiendo bien, parecen los mismos cambios que https://github.com/leoflood/ezejedrez/pull/8

Leo me mandó como task agregar al rey blanco en el medio del board solo modificando app.js; es más que nada un ejercicio que no modifica al juego. Fue para entender un par de conceptos

2021-04-23 01:04 UTC, hhaamm commented
> > No entiendo bien, parecen los mismos cambios que #8
> 
> Leo me mandó como task agregar al rey blanco en el medio del board solo modificando app.js; es más que nada un ejercicio que no modifica al juego. Fue para entender un par de conceptos

Ah, entonces tenes que mandar esta PR contra putting-pawns-in-board, no contra master. Es para no revisar los mismos cambios dos veces. Digamos que la idea sería mergear esto -> putting-pawns-in-board y despues (o antes) putting-pawns-in-board -> master.

2021-04-24 19:32 UTC, leoflood requested changes
Cambiar destino, esto no va a master, sino a putting

2021-04-24 19:56 UTC, leoflood requested changes
Cambiar destino, esto no va a master, sino a putting

2021-04-25 18:03 UTC, hhaamm approved these changes
Lo veo bien. Asumo que pasa los tests, si los pasa se puede mergear.

2021-04-26 11:52 UTC, merged